
on:
  pull_request:
    branches: [ master, development ] 

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          aarch64-unknown-linux-gnu,
          aarch64-unknown-linux-musl,
          arm-unknown-linux-gnueabi,
          armv7-unknown-linux-gnueabihf,
          mips-unknown-linux-gnu,
          mips64-unknown-linux-gnuabi64,
        ]
        feature: [kyber512, kyber768, kyber1024]
        opt: ["", 90s, "90s-fixslice"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Cross Compile Tests ${{ matrix.target }} ${{ matrix.feature }} ${{ matrix.opt }}
        uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.target }} --features "${{ matrix.feature }} ${{ matrix.opt }}" 
